[run]
  timeout = "10m"
  tests = true

[linters]
  disable-all = true
  enable = [
    "asciicheck",
    "bidichk",
    "contextcheck",
#    "copyloopvar",
    "decorder",
    "dogsled",
    "dupl",
    "dupword",
    "errcheck",
    "errname",
    "errorlint",
    "forcetypeassert",
    "gocheckcompilerdirectives",
    "gocyclo",
    "godot",
    "gofumpt",
    "gosimple",
    "govet",
    "ineffassign",
    "misspell",
    "nakedret",
    "nilerr",
    "nilnil",
    "nolintlint",
    "prealloc",
    "predeclared",
    "staticcheck",
    "stylecheck",
    "typecheck",
    "unconvert",
    "unparam",
    "unused",
    "wastedassign",
    "whitespace",
  ]

[issues]
  fix = true

[linters-settings.gofumpt]
    extra-rules = true

[linters-settings.stylecheck]
    checks = ["all", "-ST1001", "-ST1003", "-ST1005"]
