before:
  hooks:
    - go mod tidy
builds:
  -
    binary: nvdaRemoteServer
    asmflags:
      - all=-trimpath={{.Env.PWD}}
    ldflags:
      - -w -s -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - plan9
      - dragonfly
      - solaris
      - illumos
      - aix
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mips64le
      - mipsle
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      freebsd: FreeBSD
      netbsd: NetBSD
      openbsd: OpenBSD
      plan9: Plan9
      dragonfly: DragonFly
      solaris: Solaris
      aix: AIX
      386: i386
      amd64: x86_64
      arm64: aarch64
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - LICENSE
      - README.MD
      - systemd/*
      - cert.pem
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
