before:
  hooks:
    - go mod tidy
builds:
  -
    binary: nvdaRemoteServer
    ldflags:
      - -w -s -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      freebsd: FreeBSD
      netbsd: NetBSD
      openbsd: OpenBSD
      386: i386
      amd64: x86_64
      arm64: aarch64
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - LICENSE
      - README.MD
      - systemd/*
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
