on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ secrets.GO_LATEST }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cash Builder
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ secrets.GO_LATEST }}
    - name: Build
      run: go build
